name: taller1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  youtube_player_flutter: ^9.0.1
  video_player: ^2.9.2
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  url_launcher: ^6.2.6
  image_picker: ^1.2.1
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/data/peliculas1.json
